application:
  config-path: ${user.dir}/DSL
  stopInCaseOfException: true
  logging:
    displayRequestContent: false
    displayResponseContent: false
  incomingRequests:
    allowedMethodTypes: [ POST, GET ]
    headers:
      header: value
  httpCodesAllowList: [ 200, 201, 202 ]
  defaultDslInCaseOfException:
    dsl: default-dsl
    requestType: "POST"
    body:
      someVal: "Hello World"
    query:
      anotherVal: 123
  finalResponse:
      dslWithResponseHttpStatusCode: 200
      dslWithoutResponseHttpStatusCode: 300
  maxStepRecursions: 10
  CORS:
    allowedOrigins: ["https://test.buerokratt.ee", "https://admin.test.buerokratt.ee/", "https://tim.test.buerokratt.ee/"]
  DSL:
    allowedFiletypes: [".yml", ".yaml", ".tmp"]
    processedFiletypes: [".yml", ".yaml"]
    allowDslReloading: true
  internalRequests:
    allowedIPs: ["127.0.0.1", "192.168.0.1", "172.21.0.1"]
    allowedURLs: ["http://localhost/internalTest"]

spring:
  application:
    name: ruuter

logging:
  level:
    root: INFO

server:
  port: 8088,8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: ruuter
    key-password: 123456
    enabled: true

