name: Build and publish Ruuter

on:
  push:
    branches: [ dev ]
    paths:
     - '.env'

jobs:
  PackageDeploy:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Docker Setup BuildX
      uses: docker/setup-buildx-action@v2

    - name: Load environment variables
      run: |
        if [ -f .env ]; then
        export $(cat .env | grep -v '^#' | xargs)
        fi

    - name: Set image tag
      run: |
        LOWER_CASE_GITHUB_REPOSITORY=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')
        CUSTOM_TAG="${RELEASE}-${VERSION}.${BUILD}.${FIX}"
        echo "DOCKER_TAG_CUSTOM=ghcr.io/${LOWER_CASE_GITHUB_REPOSITORY}:${{CUSTOM_TAG}" >> $GITHUB_ENV
    - name: Docker Build
      run: docker image build --tag $DOCKER_TAG_CUSTOM .


    - name: Log in to GitHub container registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Push Docker image to ghcr
      run: docker push $DOCKER_TAG_CUSTOM
