name: Build and publish Ruuter

on:
  push:
    branches: [ dev ]
    paths:
     - '.env'

jobs:
  PackageDeploy:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Docker Setup BuildX
      uses: docker/setup-buildx-action@v2

    - name: Load environment variables and set them
      run: |
          if [ -f .env ]; then
            export $(cat .env | grep -v '^#' | xargs)
          fi
          echo "RELEASE=$RELEASE" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "BUILD=$BUILD" >> $GITHUB_ENV
          echo "FIX=$FIX" >> $GITHUB_ENV

          
    - name: Build Docker image
      run: |
          docker image build --tag ruuter:$RELEASE-$VERSION.$BUILD.$FIX .
          

    - name: Log in to GitHub container registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Push Docker image to ghcr
      run: |
         docker push docker.pkg.github.com/${{ github.repository_owner }}/${{ github.repository_name }}/ruuter:${{ needs.build.outputs.IMAGE_TAG }}
